CREATE TRIGGER CUSTOMER_AFTER_ACTION
 AFTER UPDATE OR DELETE OR INSERT
 ON CUSTOMER
 
 DECLARE 
 V_USERNAME VARCHAR(50);
 
 BEGIN
 SELECT USER INTO V_USERNAME FROM DUAL;
 
 IF UPDATING THEN
 INSERT INTO AUDIT_TABLE(TABLE_NAME,USERID,OPERATION_DATE, OPERATION)
 VALUES('CUSTOMER',V_USERNAME, SYSDATE, 'Before Update Operation');
 ELSIF DELETING THEN
 INSERT INTO AUDIT_TABLE(TABLE_NAME,USERID,OPERATION_DATE, OPERATION)
 VALUES('CUSTOMER',V_USERNAME, SYSDATE, 'Before Delete Operation');
 ELSIF INSERTING THEN
 INSERT INTO AUDIT_TABLE(TABLE_NAME,USERID,OPERATION_DATE, OPERATION)
 VALUES('CUSTOMER',V_USERNAME, SYSDATE, 'Before insert Operation');
 END IF;
 end;
 
 
 SELECT * FROM AUDIT_TABLE;
 
 UPDATE CUSTOMER SET FIRST_NAME = 'ELLIS' WHERE FIRST_NAME = 'sonuj';
  SELECT * FROM CUSTOMER;
  
  insert into customer values(15,'leo','remi','l','32 napa drive',null,'detroit','usa',TO_DATE('03-MAY-15','DD-MON-YY'),'NORTH');
  
  DELETE FROM CUSTOMER WHERE CUSTOMER_ID = 15;

CREATE TRIGGER CUSTOMER_AFTER_UPDATE
 AFTER UPDATE 
 ON CUSTOMER
 FOR EACH ROW
 
 DECLARE 
 V_USERNAME VARCHAR(50);
 
 BEGIN
 SELECT USER INTO V_USERNAME FROM DUAL;
 

 INSERT INTO AUDIT_TABLE(TABLE_NAME,USERID,OPERATION_DATE, OPERATION)
 VALUES('CUSTOMER',V_USERNAME, SYSDATE, 'After Update Operation row level');
 
 END;
 
 update customer set date_added = SYSDATE where CUSTOMER_ID = 12;
 
 CREATE TRIGGER CUSTOMER_AFTER_UPDATE_VALUES2
 AFTER UPDATE 
 of customer_id
 ON CUSTOMER
 FOR EACH ROW
 WHEN (OLD.REGION = 'SOUTH')
 
 DECLARE 
 V_USERNAME VARCHAR(50);
 
 BEGIN
 SELECT USER INTO V_USERNAME FROM DUAL;
 

 INSERT INTO AUDIT_LOG(USERID,OPERATION_DATE,B_CUSTOMERID,A_CUSTOMERID,B_FIRSTNAME,A_FIRSTNAME)
 VALUES(V_USERNAME, SYSDATE, :OLD.CUSTOMER_ID,:NEW.CUSTOMER_ID,:OLD.FIRST_NAME,:NEW.FIRST_NAME);
 
 END;
 
 SELECT * FROM AUDIT_LOG;
 
  SELECT * FROM CUSTOMER;
  
  UPDATE CUSTOMER SET FIRST_NAME = 'PETER A' WHERE FIRST_NAME = 'PETER';